apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerui
  template:
    metadata:
      labels:
        app: consumerui
    spec:
      containers:
        - name: consumerui
          image: jamesbub/consumerui
          command: ["/bin/sh", "-c"]
          args: ["java -jar consumerui.jar --server.port=8080"]
          env:
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: consumerui
                  key: eureka-uri
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: consumerui
spec:
  type: NodePort
  selector:
    app: consumerui
  ports:
    - port: 8081
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: consumerui
data:
  eureka-uri: "http://servicediscovery.default.svc.cluster.local/eureka/"